eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka
spring:
  application:
    name: order
  rabbitmq:
    username: renph
    password: 123456
    virtual-host: /
    addresses: 127.0.0.1:5672
    publisher-confirms: true
server:
  port: 8181
env: test
