eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka


spring:
  application:
    name: order
  rabbitmq:
    username: renph
    password: 123456
    virtual-host: /
    addresses: 127.0.0.1:5672
    publisher-confirms: true
  datasource:
    url: jdbc:mysql://139.196.106.189:3306/we_newrs?autoReconnect=true&amp;useUnicode=true
    username: we_newrs_app
    password: shuiXiang@2018

server:
  port: 8181

mybatis:
  mapper-locations: classpath*:mybatis/*Mapper.xml
  
env: test
